### ISSUE TITLE
Pick/Add a license

### ISSUE THREAD

**Issue by nofxy** [cybertunnel/Jamf-Pro-Powershell#1]
I ask that you add a license - https://choosealicense.com 

To quote the site:

"An open source license protects contributors and users. Businesses and savvy developers won’t touch a project without this protection."

I'd love to use this project internally, but can't make that decision until a license is added. Looks great, thanks!

**Comment by cybertunnel** [comment]
License has been added. Thank you for pointing it out. Hope to hear your feedback and see feature requests :)
